config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'
  #delete '/logout', to: 'sessions#destroy', as: :logout
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :users do
    resources :posts do
      resources :comments
    end
    #get '/user/account-settings', to: 'user/s#edit', as: :user_edit
    resources :admins
  end

  resources :sessions
  get '/login', to: 'sessions#new', as: :login
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> {order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  validate :picture_size

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5mb")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  enum role: [:admin, :user]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  validates :password, length: {minimum: 3}
  validates :password, confirmation: true
  validates :email, uniqueness: true, email_format: { message: 'has invalid format'}
  #validates_processing_of :image
  validate :image_size_validation

  has_many :posts, dependent: :destroy

  mount_uploader :avatar, ImageUploader

  private
    def image_size_validation
      errors[:avatar] << "should be less than 5mb" if avatar.size > 5.megabytes
    end

    def image_url
      store_dir[:avatar]
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :admin_only, :except => :show

  def index
    @user = User.all
    respond_to do |format|
      format.html
      format.json { render :json => @user }
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:success] = "User deleted!"
      redirect_to user_admins_path(current_user.id)
    else
      flash[:warning] = "Unsuccessful..."
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_role)
      flash[:notice] = "Success!"
      redirect_to user_admins_path(current_user)
    else
      flash[:danger] = "Unsuccessful!"
      render 'edit'
    end
  end

  private
    def admin_only
      unless current_user.admin?
        flash[:danger] = "Unauthorized User!"
        redirect_to user_posts_path(current_user)
      end
    end

    def user_role
      params.require(:user).permit(:role)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  private
    def not_authenticated
      flash[:warning] = "You have to authenticate to access this page."
      redirect_to root_path
    end

    #helper_method :current_users_list
     #protected
     #def current_users_list
    #   current_users.map {|u| u.username}.join(", ")
     #end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    #@post = @user.posts.find(params[:post_id])
    @post = Post.find(params[:post_id])

    if @comment = @post.comments.create(comment_params)
      @comment.user_id = current_user.id
      @comment.save
      flash[:success] = "Successfully created..."
      redirect_to user_post_path(current_user.id, @post.id)
    else
      flash[:warning] = "Unsuccessful..."
      render 'new'
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @post = @user.posts.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @post.comments.create(comment_params)
      flash[:success] = "Successfully deleted..."
      redirect_to user_post_path(@post)
    else
      flash[:warning] = "Unsuccessful..."
      render 'new'
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.joins(:user).select('posts.id, posts.user_id, posts.body, posts.created_at, users.name, users.role, users.avatar')

    respond_to do |format|
      format.html
      format.json { render :json => @post }
    end

    #@post = @post.order("created_at DESC")
    #@user_thumb = current_user.find(Post.find_by(user_id).avatar.thumb.url if User.find(@post.user_id).avatar?
  end

  def new
    #@post = Post.new
    #@post = @user.posts.build(user: current_user) if logged_in?
    @post = Post.new
  end

  def create
    @user = User.find(current_user.id)

    if @user.posts.create(post_params)
      flash[:success] = "New Post created!"
      redirect_to user_posts_path
    else
      flash[:warning] = "Unsuccessful.."
      redirect_to new_user_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    @post = @user.posts.find(params[:id])

    if @post.update_attributes(post_params)
      flash[:success] = "Post successfully updated!"
      redirect_to user_posts_path(@post)
    else
      flash[:danger] = "Operation incomplete!"
      render 'edit'
    end
  end

  def show
    #@user = User.find(current_user.id)
    @post = Post.find(params[:id])
  end

  def destroy
    @user = User.find(current_user.id)
    @post = @user.posts.find(params[:id])

    if @post.destroy
      flash[:success] = "Post deleted..."
      redirect_to user_posts_path(current_user.id)
    else
      flash[:warning] = "Unsuccessful..."
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :picture)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user_list = User.all
    respond_to do |format|
      format.html
      format.json { render :json => @user_list }
    end
  end

  def create
    if login(params[:email], params[:password], params[:remember_me])

      flash[:success] = 'Welcome Back!'
      redirect_back_or_to user_posts_path(current_user)
    else
      flash[:warning] = "Email and/or Password is incorrect."
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'Come back again!'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def index
    @user = User.all
    respond_to do |format|
      format.html
      format.json { render :json => @user }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(params[:user][:email], params[:user][:password])
      respond_with(@user)
      flash[:success] = 'Welcome!'
      redirect_to user_posts_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Successfully Updated!"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @user }
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :avatar, :remove_avatar)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_current_users.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="main-box no-header clearfix">
                <div class="main-box-body clearfix">
                    <div id="users-role">
                        <table class="table user-list">
                            <thead>
                                <tr>
                                <th><span>User</span></th>
                                <th><span>Created</span></th>
                                <th><span>Last Login</span></th>
                                <th class="text-center"><span>Online</span></th>
                                <th><span>Email</span></th>
                                <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                              <% @user.each do |u| %>
                                <tr>
                                    <td>
                                        <%= image_tag u.avatar.thumb.url, size: '50', class: 'img-circle', alt: 'Avatar' if u.avatar? %>
                                        <%= link_to u.name, user_path(u.id), class: 'a-con' %>
                                        <small class='text-muted'> - <span class="user-subhead"><%= u.role %></span></small>
                                    </td>
                                    <td><%= time_ago_in_words(u.created_at) %></td>
                                    <td><%= time_ago_in_words(u.last_login_at) %></td>
                                    <td class="text-center">
                                        <span class="label label-default"><%= time_ago_in_words(u.last_activity_at) %> </span>
                                    </td>
                                    <td>
                                        <a href="#"><%= u.email %> </a>
                                    </td>
                                    <td style="width: 20%;">
                                        <%= link_to "<span class=\'glyphicon glyphicon-pencil\'></span>".html_safe, edit_user_admin_path(current_user, u.id), class: 'a-con table-link' %></li>
                                        <a href="#" class="table-link danger">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <%= link_to "<i class=\'glyphicon glyphicon-trash\'></i>".html_safe, user_admin_path(current_user, u), class: 'a-con', method: :delete, data: {confirm: 'Are you sure?'} %>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                              <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admins/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="main-box no-header clearfix">
                <div class="main-box-body clearfix">
                    <div class="table-responsive">
                        <table class="table user-list">
                            <thead>
                                <tr>
                                <th><span>User</span></th>
                                <th><span>Email</span></th>
                                <th><span>Action</span></th>
                                <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                              <tr>
                                  <td>
                                      <%= image_tag @user.avatar.thumb.url, size: '50', class: 'img-circle', alt: 'Avatar' if @user.avatar? %>
                                      <%= link_to @user.name, user_path(@user.id), class: 'a-con' %>
                                      <small class='text-muted'> - <span class="user-subhead"><%= @user.role %></span></small>
                                  </td>
                                  <td>
                                      <a href="#"><%= @user.email %> </a>
                                  </td>
                                  <td style="width: 20%;">
                                      <a href="#" class="table-link danger">
                                          <span class="fa-stack">
                                              <i class="fa fa-square fa-stack-2x"></i>
                                              <%= link_to "<i class=\'glyphicon glyphicon-trash\'></i>".html_safe, user_admin_path(current_user, @user), class: 'a-con', method: :delete, data: {confirm: 'Are you sure?'} %>
                                          </span>
                                      </a>
                                  </td>
                              </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admins/index.html.erb
<!--<%= render 'current_users' %>-->
<script type='text/x-template' id='users-row'>
  <tr>
    <td>{{ user.name }}</td>
    <td>{{ user.created_at }}</td>
    <td>{{ user.last_login_at }}</td>
    <td>{{ user.last_activity_at }}</td>
    <td>{{ user.email }}</td>
  </tr>
</script>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="main-box no-header clearfix">
                <div class="main-box-body clearfix">
                    <div id='users'>
                        <table class="table user-list">
                            <thead>
                                <tr>
                                <th><span>User</span></th>
                                <th><span>Created</span></th>
                                <th><span>Last Login</span></th>
                                <th class="text-center"><span>Online</span></th>
                                <th><span>Email</span></th>
                                <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                              <tr is='users-row'
                                  v-for='user in users'
                                  :user='user'>
                              </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/comments/_commentForm.html.erb
<%= form_for [current_user, @post, @post.comments.build] do |f| %>
  <div class='form-group'>
    <%= f.label :Add_comments %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <div class='pull-right'>
      <%= f.submit 'Post', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'frontend-vue' %>
  </head>

  <body>
    <div class='header'>
      <nav class='navbar navbar-findcond navbar-fixed-top' role="navigation">
        <div class="container">
            <div class="navbar-header">
              <a href='#' class='navbar-brand'>Magical</a>
            </div>

            <div id="navbar">
              <ul class="nav navbar-nav">
              <% if current_user %>
                    <li><%= link_to 'Posts', user_posts_path(current_user) %></li>
                    <li><a href='#'>About</a></li>
              <% else %>
                    <li><%= link_to 'Create Account', sign_up_path%></li>
                    <li><%= link_to "<span class=\'glyphicon glyphicon-log-in\'></span> Login".html_safe, login_path %></li>
              <% end %>
              </ul>
              <% if current_user%>
                <ul class="nav navbar-nav navbar-right">
                  <% if current_user.admin? %>
                    <li><%= link_to "<span class=\'glyphicon glyphicon-book\'></span> Admin Management".html_safe, user_admins_path(current_user) %></li>
                  <% end %>
                  <li><%= link_to "<span class=\'glyphicon glyphicon-wrench\'></span> Account Settings".html_safe, edit_user_path(current_user) %></li>
                  <li><%= link_to "<span class=\'glyphicon glyphicon-user\'></span>".html_safe+ ' ' + current_user.name, user_path(current_user), class: 'dock-item' %></li>
                  <li><%= link_to "<span class=\'glyphicon glyphicon-log-out\'></span> Logout".html_safe, session_path(session),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %></li>
                </ul>
              <% end %>
            </div>
        </div>
      </nav>
    </div>

    <div class="body" style="margin-top:70px;">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        <%end%>
      <%= yield %>

    </div>

    <div class='footer'>
      <div class='container'>
        <center class="center-con">
          <a href="#">About</a> |
          <a href="#">Terms of Service</a> |
          <a href="#">Privacy</a>
          <p style="color: #9d9d9d;margin-top:5px;margin-bottom:10px;" class="text-center muted">© 2017 Magical Project. All rights reserved </p>
        </center>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/posts/_textform.html.erb
<!--session_pages_path(current_user.id)-->
<%= form_for [current_user, @post] do |f| %>
  <div class="form-group">
    <%= f.label :body %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', required: true %>
    <div class='pull-right'>
      <span class='picture'>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
    </div>
  </div>
    <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

<script type='text/javascript'>
  $('$post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/edit.html.erb
<% provide(:button_text, 'Update') %>

<h1 class='text-center'>Update blog</h1>
<div class='container'>
  <%= render 'textform' %>
</div>

app/views/posts/index.html.erb
<script type='text/x-template' id='post-list'>
  <div class="panel panel-default">
    <div class="panel-body">
      <li class='media'>
        <div class='media-left'>
          <img class='img img-circle img-resize' v-bind:src="'/uploads/user/avatar/' + post.user_id + '/'+ post.avatar"></img>
        </div>
        <div class='media-body'>
          <h4 class='media-heading'>

            <b>{{ post.name }}</b>
            <br>
            <small class='text-muted'>

              <em>- {{ post.role }} posted {{ post.created_at }} ago. <span class='glyphicon glyphicon-time'></span></em>
            </small>
          </h4>
        </div>
        <div class='media-right'>
          <a href='#'></a>

        </div>
      </li>
      <br>
      <p class="lead text-justify">
         {{ post.body }} <br>
        <div class='text-center'>

        </div>
      </p>
      <hr></hr>
      <div class="pull-left">
        <a><b>Like</b></a>  
        <a><b>Share</b></a>
      </div>
      <div class="pull-right">

      </div>
    </div>
  </div>
</script>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <!--<div id='prof'>
        <profile></profile>
      </div>-->
      <%= link_to 'Create Blog', new_user_post_path(current_user.id), class: 'btn btn-success' %>
      <!--sidebar-->
      <div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
					<%= image_tag root_url + "/#{current_user.avatar}", class: 'img-responsive' %>
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<%= current_user.name %>
					</div>
					<div class="profile-usertitle-job">
						Developer
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-success btn-sm">Follow</button>
					<button type="button" class="btn btn-danger btn-sm">Message</button>
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
							<i class="glyphicon glyphicon-home"></i>
							Overview </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-user"></i>
							Account Settings </a>
						</li>
						<li>
							<a href="#" target="_blank">
							<i class="glyphicon glyphicon-ok"></i>
							Tasks </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-flag"></i>
							Help </a>
						</li>
					</ul>
				</div>
				<!-- END MENU -->
			</div>

    </div>
    <div class="col-md-6">
      <!--<div id='write-post'>
        <writepost></writepost>
      </div>-->
      <div id='posts'>
        <div is='post-list' v-for='post in posts' :post='post'>

        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class='panel panel-default'>
        <ul class='list-group' id='contact-list'>
          <li class='list-group-item'>
            <!--image-->
            <!--name-->
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:button_text, 'Create Post') %>

<h1 class='text-center'>Create new blog</h1>
<div class='container'>
  <%= render 'textform' %>
</div>

<div class="widget-area no-padding blank">
  <div class="status-upload">
    <form>
      <textarea placeholder="What are you doing right now?" ></textarea>
      <ul>
        <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Audio"><i class="fa fa-music"></i></a></li>
        <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Video"><i class="fa fa-video-camera"></i></a></li>
        <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Sound Record"><i class="fa fa-microphone"></i></a></li>
        <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Picture"><i class="fa fa-picture-o"></i></a></li>
      </ul>
      <button type="submit" class="btn btn-success green"><i class="fa fa-share"></i> Share</button>
    </form>
  </div><!-- Status Upload  -->
</div><!-- Widget Area -->

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
					<li class='media'>
						<div class='media-left'>
							<% if User.find(@post.user_id).avatar? %>
								<%= image_tag User.find(@post.user_id).avatar.thumb.url, size: '50', class: 'img-circle' %>
							<% end %>
						</div>
						<div class='media-body'>
							<h4 class='media-heading'>
								<b><%= User.find(@post.user_id).name %></b>
								<br>
								<small class='text-muted'>
									<em>posted <%= time_ago_in_words(@post.created_at) %> ago. <span class='glyphicon glyphicon-time'></span></em>
								</small>
							</h4>
						</div>
						<div class='media-right'>
							<% if current_user.id == @post.user_id %>
	              <%= link_to "<span class=\'glyphicon glyphicon-wrench\'></span>".html_safe, edit_user_post_path(current_user, @post), class: 'a-con' %>
	              <%= link_to "<span class=\'glyphicon glyphicon-trash\'></span>".html_safe, user_post_path(@post), class: 'a-con',
	                              method: :delete,
	                              data: { confirm: 'Are you sure?' } %>
	            <% end %>
						</div>
					</li>
          <br>
						<p class='lead text-justify'>
							<%= @post.body %><br></br>
							<div class='text-center'>
								<%= image_tag @post.picture.url, class: 'img-thumbnail' if @post.picture? %>
							</div>
						</p>
            <hr></hr>
            <!--<div class="pull-left">
							<h5><b>Comments:</b></h5>
						</div>
						<div class="pull-right">
						</div>-->

						<!-- Fluid width widget -->
							<div class="panel-heading">
									<h3 class="panel-title">
											<span class="glyphicon glyphicon-comment"></span> 
											Recent Comments
									</h3>
							</div>
							<div class="panel-body">
								<ul class="media-list">
									<% @post.comments.each do |c| %>
									<li class="media">
											<div class="media-left">
												<%= image_tag User.find(c.user_id).avatar.thumb.url, size: '50' ,class: 'd-flex mr-3 img-circle', alt: 'Avatar' if User.find(c.user_id).avatar?%>
											</div>
											<div class="media-body">
													<h5 class="media-heading">
															<b><%= User.find(c.user_id).name %></b>
															<br>
															<small class='text-muted'>
																<em>commented <%= time_ago_in_words(c.created_at) %> ago. </em><span class='glyphicon glyphicon-time'></span>
															</small>
													</h5>
													<p class='text-justify'>
															<%= c.body %>
													</p>
											</div>
									</li>
									<% end %>
								</ul>
							</div>
							<!-- End fluid width widget -->
						<%= render 'comments/commentForm' %>
      	</div>
    	</div>
    <div class="col-md-2">

    </div>
  </div>
</div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, accept: 'image/jpeg,image/gif,image/png' %>
    <% if f.object.avatar? %>
     <%= image_tag f.object.avatar.thumb.url %>
     <%= f.label :remove_avatar %>
     <%= f.check_box :remove_avatar %>
   <% end %>
  </div>
  <%= f.submit yield(:button_form), class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Update Account') %>
<% provide(:button_form, 'Update') %>
<% provide(:url, user_path(current_user)) %>
<% provide(:method, 'PUT') %>

<div class='container'>
  <h1 class='text-center'>UPDATE</h1>
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<% provide(:button_form, 'Create Account') %>

<h1 class='text-center'> Registration </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-5'>
      <div class='media'>
        <div class='media-left'>
          <%= image_tag @user.avatar.url, size: '180', class: 'img img-responsive img-thumbnail', alt: 'avatar' if @user.avatar? %>
        </div>
        <div class='media-right'>
          <div class='text-uppercase'><b><%= @user.name %></b></div>
          <div class='small text-muted'><%= @user.email %></div>
          <hr>
          <div class='media'>
            <div class='media-left'>
              Followers <span class='badge badge-important'>5</span>
              <p>Posts <span class='badge badge'><%= @user.posts.count %></span></p>
            </div>
            <div class='media-right'>
              Followed <span class='badge badge-success'>9</span>
            </div>
          </div>
        </div>
      </div>
      <hr></hr>

      <ul class="nav nav-pills nav-stacked admin-menu" >
        <li class="active"><a href="" data-target-id="profile"><i class="glyphicon glyphicon-user"></i> Profile</a></li>
        <li><a href="" data-target-id="change-password"><i class="glyphicon glyphicon-lock"></i> Change Password</a></li>
        <li><a href="" data-target-id="settings"><i class="glyphicon glyphicon-cog"></i> Settings</a></li>
        <li><a href="" data-target-id="logout"><i class="glyphicon glyphicon-log-out"></i> Logout</a></li>
      </ul>

    </div>
    <div class='col-md-7'>
      <% @user.posts.each do |post| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <li class='media'>
            <div class='media-left'>
              <%= image_tag @user.avatar.thumb.url, size: '50', class: 'img-circle', alt: 'Avatar' if @user.avatar?%>
            </div>
            <div class='media-body'>
              <h4 class='media-heading'>
                <b><%= @user.name %></b>
                <br>
                <small class='text-muted'>
                  <em>posted <%= time_ago_in_words(post.created_at) %> ago. <span class='glyphicon glyphicon-time'></span></em>
                </small>
              </h4>
              <center><h4 class='text-uppercase'><%= post.title %></h4></center>
            </div>
            <div class='media-right'>
              <%= link_to 'more...', user_post_path(current_user, post), class: 'a-con' %>
            </div>
          </li>
          <br>
          <p class="lead text-justify">
            <%= post.body %><br></br>
            <div class='text-center'>
              <%= image_tag post.picture.url, class: 'img-thumbnail' if post.picture? %>
            </div>
          </p>
          <hr></hr>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>